version: "2"
services:
  load-balancer:
    image: "rastasheep/ubuntu-sshd:18.04"
    ports:
      - "2201:22"
      - "8001:80"
    hostname: load-balancer
  web1:
    image: "rastasheep/ubuntu-sshd:18.04"
    ports:
      - "2202:22"
      - "8002:80"
    hostname: web-1
  web2:
    image: "rastasheep/ubuntu-sshd:18.04"
    ports:
      - "2203:22"
      - "8003:80"
    hostname: web-2
