---
- hosts: load_balancing
  become: true
  roles:
    - load-balancer
- hosts: web
  become: true
  roles:
    - role: web-deployer
#      repo: 'https://github.com/banago/simple-php-website.git'
      repo: 'https://github.com/KamranAzeem/simple-php-website.git'